# Generated by Django 5.0 on 2023-12-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_projectvolunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
