# Generated by Django 5.0 on 2023-12-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_application_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
