# Generated by Django 5.0 on 2023-12-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_volunteer_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_text',
            field=models.TextField(null=True),
        ),
    ]
